name: mixup
services:
  webserver:
    build:
      context: './docker/server'
      args:
        - UID=${UID:-1000}
        - PHP_VERSION=${PHP_VERSION:-8}
    volumes:
      - ./:/var/www/html/
    restart: always
    ports:
      - 8000:80
